version: "3.9"

services:
  postgres:
    image: postgres:17.2
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laba_3
    ports:
      - "5432:5432"
    networks:
      postgres_net:
        ipv4_address: 172.20.0.100
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin_bsbd:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
    - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
    - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres_net
    restart: unless-stopped

networks:
  postgres_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24